### ISSUE TITLE
Wrong max length in setNextInteger

### ISSUE THREAD

**Issue by anthonygraignic** [devnied/Bit-lib4j#4]
Hi,
In BitUtils, the method setNextInteger only accepts a pLength <= 31, or an Integer can be 32 bits according to [Integer javadoc](http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html#SIZE).
So an IllegalArgumentException prevents to set an Integer of 32 bits length which is quite problematic

**Comment by devnied** [comment]
Fixed in 1.4.11
Thanks,
