### ISSUE TITLE
Negative integer/long support

### ISSUE THREAD

**Issue by dima-falcore** [devnied/Bit-lib4j#7]
I'm tyring to use nagative values with no luck

```
byte[] array = new byte[1];
BitUtils bit = new BitUtils(array);
bit.setNextInteger(-2, 8);
byte[] data = bit.getData();
BitUtils bit2 = new BitUtils((data));
int nextInteger = bit2.getNextInteger(8)
```

nextInteger will 254, it seems that the getter doesnt use the sign bit. 
Or maybe i'm doing something wrong?

**Comment by devnied** [comment]
Yes, currently the library doesn't support the signed type.

**Comment by dima-falcore** [comment]
Do you have any workaround? I really like the ease of the library.
